version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
      - NODE_ENV=dev
    volumes:
      - .:/app
      - /app/node_modules
    container_name: node_python_csv_server
    working_dir: /app
    ports:
      - 3000:3000
    command: node_modules/nodemon/bin/nodemon.js ./index.js
